version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "422391363513"
    CLUSTER: "terapias-core-prod"
    SERVICE: "agendas-core-prod"
    IMAGE_REPO_NAME: "agenda-core-prod"
    IMAGE_TAG: "latest"

phases: 
  pre_build:
    commands:
      - aws --version
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 422391363513.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building Docker image...."
      - docker build -t agenda-core-prod .
      - echo "Tagging Docker image..."
      - docker tag agenda-core-prod:latest 422391363513.dkr.ecr.us-east-1.amazonaws.com/agenda-core-prod:latest
      - echo "Pushing Docker image to repository..."
      - docker push 422391363513.dkr.ecr.us-east-1.amazonaws.com/agenda-core-prod:latest
      
  post_build:
    commands:
      - echo "Writing image definitions file..."
      - printf '{"ImageURI":"%s"}'422391363513.dkr.ecr.us-east-1.amazonaws.com/agenda-core-prod:latest > imageDetail.json
      - aws ecs update-service --cluster $CLUSTER --service $SERVICE --force-new-deployment 


artifacts:
  files:
    - imageDetail.json

