// Generated by https://quicktype.io

export type DeepPartial<T> = T extends object
   ? {
        [P in keyof T]?: DeepPartial<T[P]>;
     }
   : T;

export interface NewInvoice
   extends DeepPartial<{
      status: string;
      detail: Detail;
      invoicer: Invoicer;
      primary_recipients: PrimaryRecipient[];
      items: Item[];
      configuration: Configuration;
      amount: Amount;
   }> {}

export interface Amount {
   breakdown: Breakdown;
}

export interface Breakdown {
   custom: Custom;
   shipping: Shipping;
   discount: BreakdownDiscount;
}

export interface Custom {
   label: string;
   amount: MinimumAmountDue;
}

export interface MinimumAmountDue {
   currency_code: string;
   value: string;
}

export interface BreakdownDiscount {
   invoice_discount: InvoiceDiscount;
}

export interface InvoiceDiscount {
   percent: string;
}

export interface Shipping {
   amount: MinimumAmountDue;
   tax: Tax;
}

export interface Tax {
   name: string;
   percent: string;
}

export interface Configuration {
   partial_payment: PartialPayment;
   allow_tip: boolean;
   tax_calculated_after_discount: boolean;
   tax_inclusive: boolean;
   template_id: string;
}

export interface PartialPayment {
   allow_partial_payment: boolean;
   minimum_amount_due: MinimumAmountDue;
}

export interface Detail {
   currency_code: string;
   invoice_number: string;
   reference: string;
   invoice_date: string;
   note: string;
   term: string;
   memo: string;
   payment_term: PaymentTerm;
}

export interface PaymentTerm {
   term_type: string;
   due_date: string;
}

export interface Invoicer {
   name: Name;
   address: Address;
   email_address: string;
   phones: Phone[];
   website: string;
   tax_id: string;
   logo_url: string;
   additional_notes: string;
}

export interface Address {
   address_line_1: string;
   address_line_2?: string;
   admin_area_2: string;
   admin_area_1: string;
   postal_code: string;
   country_code: string;
}

export interface Name {
   given_name: string;
   surname: string;
}

export interface Phone {
   country_code: string;
   national_number: string;
   phone_type: string;
}

export interface Item {
   name: string;
   description?: string;
   quantity: string;
   unit_amount: MinimumAmountDue;
   tax: Tax;
   discount: ItemDiscount;
   unit_of_measure: string;
}

export interface ItemDiscount {
   percent?: string;
   amount?: MinimumAmountDue;
}

export interface PrimaryRecipient {
   billing_info: BillingInfo;
   shipping_info: ShippingInfo;
}

export interface BillingInfo {
   name: Name;
   address: Address;
   email_address: string;
   phones: Phone[];
   additional_info_value: string;
}

export interface ShippingInfo {
   name: Name;
   address: Address;
}
